import type { Metadata } from "next";
// import localFont from "next/font/local";
import React from "react";
import { Balsamiq_Sans } from "next/font/google";
import "./globals.css";
import Grid from "./components/grid";

const balsamiq = Balsamiq_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-balsamiq",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Grid />
      <body className={`${balsamiq.variable} antialiased`}>{children}</body>
    </html>
  );
}
